[".dircolors/dircolors.256dark"]
  type = "file"
  url = "https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.256dark"
  refreshPeriod = "168h"
[".dircolors/dircolors.ansi-dark"]
  type = "file"
  url = "https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark"
  refreshPeriod = "168h"
[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
